SightseeingApp/Models/UserData.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SightseeingApp.Models
{
    public class UserData
    {
        public int Id { get; set; }

        [Display(Name = "Koszt")]
        public double Cost { get; set; }

        [Display(Name = "Czas")]
        public double Time { get; set; }

        public Category Category { get; set; } //navigation property

        [Display(Name = "Zainteresowania")]
        public byte CategoryId { get; set; }

        public List<byte> Interests { get; set; }

        
        public TransportMode TransportMode { get; set; }

        [Display(Name = "Środek transportu")]
        public byte TrasportModeId { get; set; }
        

    }
}

SightseeingApp/Controllers/UserDataController.cs
using GAF;
using SightseeingApp.Models;
using SightseeingApp.Service;
using SightseeingApp.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SightseeingApp.Controllers
{
    // odbierać dane od użytkownika
    public class UserDataController : Controller
    {
        private AppRepository _userDataRepository;
        private AlghService _alghService;
        

        public UserDataController()
        {
            _userDataRepository = new AppRepository();
            _alghService = new AlghService();
         
        }


        public ActionResult Index()
        {
           return View();

        }
        public ActionResult UserDataForm()
        {
          var selectedItems =  _userDataRepository.GetCategories();

          var viewModel = new NewUserDataViewModel();

          viewModel.GetInterests = _userDataRepository.GetCategories().Select(c => new Category { Id = c.Id, CategoryName = c.CategoryName });

          viewModel.GetTransportMode = _userDataRepository.GetTransportModes().Select(c => new TransportMode { Id = c.Id, TransportModeName = c.TransportModeName });


           return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async System.Threading.Tasks.Task<ActionResult> SaveAsync(NewUserDataViewModel viewModel)
        {
            var chromosome = await _alghService.CreateChromosomeAsync(viewModel.userData);

            var population = await _alghService.CreatePopulationAsync(viewModel.userData);
            var fitness = _alghService.CalculateFitness(chromosome);
            var ag = _alghService.CreateGeneticAlgorithm(population);
            var fittest = ag.Population.GetTop(1)[0];
            var fittest2 = ag.Population.GetTop(2)[0];
            var elites = ag.Population.GetElites();
            var maxfitness = ag.Population.MaximumFitness;
            var minfitness = ag.Population.MinimumFitness;
            var ag2 = _alghService.CreateGeneticAlgorithm(ag.Population);


            return RedirectToAction("ShowResult", "Result");

        }
    }
}

SightseeingApp/Views/UserData/Index.cshtml
@model IEnumerable<SightseeingApp.Models.UserData>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Cost)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Time)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CategoryId)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Cost)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Time)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CategoryId)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

SightseeingApp/Views/UserData/UserDataForm.cshtml
@model SightseeingApp.ViewModels.NewUserDataViewModel


@using (Html.BeginForm("SaveAsync", "UserData")) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Podaj czas i koszt</h4>
        
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.userData.Cost, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.userData.Cost, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.userData.Cost, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.userData.Time, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.userData.Time, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.userData.Time, "", new { @class = "text-danger" })
            </div>
        </div>

             
                    <div class="form-group">
                        @Html.LabelFor(model => model.userData.CategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.userData.CategoryId, Model.GetInterests.Select(x => new SelectListItem { Text = x.CategoryName, Value = x.Id.ToString() }), new { @class = "form-control chosen-select", @multiple = "true" })
                            @Html.ValidationMessageFor(model => model.userData.CategoryId, "", new { @class = "text-danger" })
                        </div>
                    </div>


                    <div class="form-group">
                        @Html.LabelFor(model => model.userData.TrasportModeId, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.userData.TrasportModeId, Model.GetTransportMode.Select(x => new SelectListItem { Text = x.TransportModeName, Value = x.Id.ToString() }), new { @class = "form-control chosen-select", @multiple = "true" })
                            @Html.ValidationMessageFor(model => model.userData.TrasportModeId, "", new { @class = "text-danger" })
                        </div>
                    </div>



                    @Html.HiddenFor(m => m.userData.Id)

                
      

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Znajdź trasę" class="btn btn-default" />
            </div>
        </div>

    </div>
}

<div>
    @Html.ActionLink("Wróć do Strony Głównej", "Index")
</div>

<script>
    $('.chosen-select').chosen();
</script>